---
title: "Amazon reviews"
output:
  pdf_document: default
  html_notebook: default
  html_document: default
---


```{r}

#Load packages
library(dplyr)
library(tidyr)
library(readr)
library(ngram)
library(ggplot2)
library(vioplot)
library(tm)
library(SnowballC)
library(stringr)
library(caTools)
library(rpart)
library(rpart.plot)
library(ROCR)
library(randomForest)
library(caret)
library(e1071)
library(DMwR)

#Import dataset
amazon_original <- read.csv("Reviews2.csv", stringsAsFactors = F)

```

```{r}
#Review data, confirmed no missing values present
summary(amazon_original)
```

```{r}
#Filter out Neutral Scores (Score = 3) and remove the ID column
amazon_noneutral <- filter(amazon_original, Score != 3)
#table(amazon_noneutral$Score)

amazon_noneutral <- select(amazon_noneutral, -Id)

```


```{r}
#Create new rating_negative variable
amazon_categories <- amazon_noneutral %>% mutate(rating_negative = case_when(
  .$Score == 5 ~ 0,
  .$Score == 4 ~ 0,
  .$Score == 2 ~ 1,
  .$Score == 1 ~ 1))

amazon_categories$rating_negative <- as.factor(amazon_categories$rating_negative)

write.csv(amazon_categories, file = "amazon_clean.csv")

#Create a new column which contains count of characters from Text column
amazon_categories <- mutate(amazon_categories, TextChar = nchar(Text))

#Create a new colomn which contains count of words from Text column
amazon_categories <- mutate(amazon_categories, WordCount = str_count(amazon_categories$Text, '\\w+'))

```


```{r}
#histogram showing distribution of Score across all reviews
ggplot(amazon_categories, aes(x = Score)) +
  geom_histogram() +
  ggtitle("Count of Review Score") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(y= "Total Count", x = "Review Score")


```

```{r}

#Boxplot showing distribtion of # of characters by Rating_negative
ggplot(amazon_categories, aes(x = rating_negative, y = TextChar, group = rating_negative)) + 
  geom_boxplot() +
  ggtitle("# of Characters by Rating_Negative") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(y= "Character Count", x = "Rating Negative (1 = Yes, 0 = No)")

```


```{r}
#Create sample

prop.table(table(amazon_categories$rating_negative))
sample <- amazon_categories[sample(nrow(amazon_categories), size = 5000, replace = FALSE),]
prop.table(table(sample$rating_negative))

```



```{r}
#Create a corpus for summary and another for text
corpus_summary = Corpus(VectorSource(sample$Summary))
corpus_text = Corpus(VectorSource(sample$Text))

#Preprocessing: Remove stopwords, and stem.
#corpus_summary = tm_map(corpus_summary, removeWords, stopwords("english"))
#corpus_text = tm_map(corpus_text, removeWords, stopwords("english"))
corpus_summary = tm_map(corpus_summary, stemDocument)
corpus_text = tm_map(corpus_text, stemDocument)

#Build document term matrices, remove sparse terms
dtm_summary = DocumentTermMatrix(corpus_summary)
dtm_summary = removeSparseTerms(dtm_summary, 0.99)

dtm_text = DocumentTermMatrix(corpus_text)
dtm_text = removeSparseTerms(dtm_text, 0.9)
```

```{r}
#dtm_summary
#dim(dtm_summary)
#dtm_text
#dim(dtm_text)
```


```{r}

#Create dataframe containing frequencies
Terms_summary = as.data.frame(as.matrix(dtm_summary))
Terms_text = as.data.frame(as.matrix(dtm_text))

#Rename columns so source is easily identifiable

colnames(Terms_summary) <- paste("Sum", colnames(Terms_summary), sep = "_")
colnames(Terms_text) <- paste("Text", colnames(Terms_text), sep = "_")

# Append the dependent variable and char count from original data set
Terms_summary$rating_negative = sample$rating_negative
Terms_summary$TextChar = sample$TextChar


#combine summary with text
combined = cbind(Terms_summary, Terms_text, deparse.level = 1)

```

```{r}
#Adding columns

combined$Exclamation_summary = str_count(sample$Summary, pattern = "!") #count of exclamation marks
combined$CAPS_summary = str_count(sample$Summary, "\\b[A-Z]{2,}\\b") #count of words in CAPS
combined$summary_total = sapply(gregexpr("[[:alpha:]]+", sample$Summary), function(x) sum(x > 0)) #total # of words

combined$Exclamation_summary_proportion = round(combined$Exclamation_summary / combined$summary_total, digits = 4) #proportion of exclamation points to total # of words

is.na(combined$Exclamation_summary_proportion) <- do.call(cbind,lapply(combined$Exclamation_summary_proportion, is.infinite))

combined$CAPS_summary_proportion = combined$CAPS_summary / combined$summary_total #proportion of CAPS words to total # of words

is.na(combined$CAPS_summary_proportion) <- do.call(cbind,lapply(combined$CAPS_summary_proportion, is.infinite))

combined$Exclamation_text = str_count(sample$Text, pattern = "!") #count of exclamation marks
combined$CAPS_text = str_count(sample$Text, "\\b[A-Z]{2,}\\b") #count of words in CAPS
combined$text_total = sapply(gregexpr("[[:alpha:]]+", sample$Text), function(x) sum(x > 0)) #total # of words

combined$Exclamation_text_proportion = round(combined$Exclamation_text / combined$text_total, digits = 4) #proportion of exclamation points to total # of words

is.na(combined$Exclamation_text_proportion) <- do.call(cbind,lapply(combined$Exclamation_text_proportion, is.infinite))

combined$CAPS_text_proportion = combined$CAPS_text / combined$summary_total #proportion of CAPS words to total # of words

is.na(combined$CAPS_text_proportion) <- do.call(cbind,lapply(combined$CAPS_text_proportion, is.infinite))

#replace all NAs with 0
combined$Exclamation_summary_proportion[is.na(combined$Exclamation_summary_proportion)] <- 0
combined$CAPS_summary_proportion[is.na(combined$CAPS_summary_proportion)] <- 0
combined$Exclamation_text_proportion[is.na(combined$Exclamation_text_proportion)] <- 0
combined$CAPS_text_proportion[is.na(combined$CAPS_text_proportion)] <- 0

#ncol(combined)
#nearZeroVar(combined)
combined <- combined[,-nearZeroVar(combined)]
#ncol(combined)

```

```{r}

#Barplot showing Summary proportion of exclamation marks to total words by rating_negative
plot_Exclam_summary = combined %>% group_by(rating_negative) %>% summarise(Exclamation_summary_proportion = sum(Exclamation_summary)*100/sum(summary_total))

ggplot(plot_Exclam_summary,aes(x=rating_negative,y=Exclamation_summary_proportion))+
  geom_bar(stat="identity")+
ggtitle("Summary - Proportion of exclamation marks to total words") +
 theme(plot.title = element_text(hjust = 0.5)) +
 labs(y= "Proportion as a percent", x = "Rating_negative (1 = Yes, 0 = No)")

```
 
 
```{r}
#Barplot showing Text proportion of exclamation marks to total words by rating-negative

plot_Exclam_text = combined %>% group_by(rating_negative) %>% summarise(Exclamation_text_proportion = sum(Exclamation_text)*100/sum(text_total))

ggplot(plot_Exclam_text,aes(x=rating_negative,y=Exclamation_text_proportion))+
  geom_bar(stat="identity")+
ggtitle("Text - Proportion of exclamation marks to total words") +
 theme(plot.title = element_text(hjust = 0.5)) +
 labs(y= "Proportion as a percent", x = "Rating_negative (1 = Yes, 0 = No)")



```

 
 
 
```{r}
#Barplot showing Summary proportion of CAPS words to total words by rating_negative
plot_CAPS_summary = combined %>% group_by(rating_negative) %>% summarise(CAPS_summary_proportion = sum(CAPS_summary)*100/sum(summary_total))

ggplot(plot_CAPS_summary,aes(x=rating_negative,y=CAPS_summary_proportion))+
  geom_bar(stat="identity")+
ggtitle("Summary - Proportion of CAPS to total words") +
 theme(plot.title = element_text(hjust = 0.5)) +
 labs(y= "Proportion as a percent", x = "Rating_negative (1 = Yes, 0 = No)")

```


```{r}
#Barplot showing Text proportion of CAPS words to total words by rating_negative
plot_CAPS_text = combined %>% group_by(rating_negative) %>% summarise(CAPS_text_proportion = sum(CAPS_text)*100/sum(summary_total))

ggplot(plot_CAPS_text,aes(x=rating_negative,y=CAPS_text_proportion))+
  geom_bar(stat="identity")+
ggtitle("Text - Proportion of CAPS to total words") +
 theme(plot.title = element_text(hjust = 0.5)) +
 labs(y= "Proportion as a percent", x = "Rating_negative (1 = Yes, 0 = No) ")
```


```{r}
#Create training and test datasets
#set.seed(12)
split = sample.split(combined$rating_negative, SplitRatio = 0.7)
Train = subset(combined, split == TRUE)
Test = subset(combined, split == FALSE)
#head(Train)
#colnames(Train)
```


```{r}
#Establish baseline

table(combined$rating_negative)

baseline = 4244/5000
baseline
```


```{r}
#Create random forest model
set.seed(10)
model_rf <- caret::train(rating_negative ~ .,
                         data = Train,
                         method = "rf",
                         preProcess = c("scale", "center"),
                         trControl = trainControl(method = "repeatedcv", 
                                                  number = 10, 
                                                  repeats = 10, 
                                                  verboseIter = FALSE))
```


```{r}
final <- data.frame(actual = Test$rating_negative,
                    predict(model_rf, newdata = Test, type = "prob"))

final$predict <- ifelse(final$X1 > 0.5, 1, 0)

cm_original <- confusionMatrix(final$predict, Test$rating_negative)
cm_original

```


```{r}
#Create ROC curve
ROCRpred = prediction(final$predict, final$actual)
ROCRperf = performance(ROCRpred, "tpr", "fpr")
plot(ROCRperf, colorize = TRUE, print.cutoffs.at=seq(0, 1, 0.1), text.adj=c(-0.2, 1.7))
```

```{r}
#Create random forest model - smote
set.seed(10)
model_rf_smote <- caret::train(rating_negative ~ .,
                         data = Train,
                         method = "rf",
                         preProcess = c("scale", "center"),
                         trControl = trainControl(method = "repeatedcv", 
                                                  number = 10, 
                                                  repeats = 10, 
                                                  verboseIter = FALSE,
                                                  sampling = "smote"))
```

```{r}

final_smote <- data.frame(actual = Test$rating_negative,
                    predict(model_rf_smote, newdata = Test, type = "prob"))

final_smote$predict_smote <- ifelse(final_smote$X1 > 0.47, 1, 0)

cm_smote <- confusionMatrix(final_smote$predict_smote, Test$rating_negative)
cm_smote

```

```{r}
#Create ROC curve
ROCRpred = prediction(final_smote$predict, final_smote$actual)
ROCRperf = performance(ROCRpred, "tpr", "fpr")
plot(ROCRperf, colorize = TRUE, print.cutoffs.at=seq(0, 1, 0.1), text.adj=c(-0.2, 1.7))

```


```{r}
#Define logistic regression model
ratingLog = glm(rating_negative ~ ., data = Train, family = binomial)

```

```{r}
#coef(summary(ratingLog))
```

```{r}
ratingLog.tab <- coef(summary(ratingLog))
ratingLog.tab[, "Estimate"] <- exp(coef(ratingLog))
ratingLog.tab
```

```{r}
#Create prediction

predictTrain = predict(ratingLog, type = "response")
#summary(predictTrain)

```

```{r}
#Confusion matrix
table(Train$rating_negative, predictTrain > 0.2)

```

```{r}
#Compute TPR and TNR
tpr = 380 / (380 + 149)
tnr = 2470 / (2470 + 501)
acc = (2470 + 380) / 5000
tpr
tnr
acc
```

```{r}
#Create prediction

predictTest = predict(ratingLog, newdata = Test, type = "response")

```

```{r}
#Confusion matrix
table(Test$rating_negative, predictTest > 0.2)

```


```{r}
#Compute TPR and TNR
tpr_test = 380 / (380 + 149)
tnr_test = 2470 / (2470 + 501)
acc_test = (2470 + 380) / 5000
tpr_test
tnr_test
acc_test
```


```{r}
#Create decision tree model
set.seed(10)
model_DT <- caret::train(rating_negative ~ .,
                         data = Train,
                         method = "rpart",
                         preProcess = c("scale", "center"),
                         trControl = trainControl(method = "repeatedcv", 
                                                  number = 10, 
                                                  repeats = 10, 
                                                  verboseIter = FALSE))
```

```{r}

final_DT <- data.frame(actual = Test$rating_negative,
                    predict(model_DT, newdata = Test, type = "prob"))

final_DT$predict <- ifelse(final_DT$X1 > 0.2, 1, 0)

cm_DT <- confusionMatrix(final_DT$predict, Test$rating_negative)
cm_DT

```


